services:
  neo4j:
    image: neo4j:5-community
    container_name: sample-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
    volumes:
      - sample_neo4j_data:/data

volumes:
  sample_neo4j_data:
